"""criação das tabelas

Revision ID: 47d6fe0bd115
Revises: 
Create Date: 2025-05-06 14:13:51.973065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '47d6fe0bd115'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_movimentacoes')
    op.drop_table('tb_clientes')
    op.drop_table('tb_fornecedores')
    op.alter_column('tb_produtos', 'pro_data_cadastro',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tb_produtos', 'pro_data_cadastro',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.create_table('tb_fornecedores',
    sa.Column('for_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('for_nome', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('for_cnpj', mysql.VARCHAR(length=18), nullable=True),
    sa.Column('for_contato', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('for_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tb_clientes',
    sa.Column('cli_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cli_cpf', mysql.VARCHAR(length=18), nullable=True),
    sa.Column('cli_nome', mysql.VARCHAR(length=45), nullable=True),
    sa.PrimaryKeyConstraint('cli_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tb_movimentacoes',
    sa.Column('mov_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('mov_pro_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mov_cli_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mov_motivo', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('mov_data', mysql.DATETIME(), nullable=True),
    sa.Column('mov_quantidade', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['mov_cli_id'], ['tb_clientes.cli_id'], name='tb_movimentacoes_ibfk_2'),
    sa.ForeignKeyConstraint(['mov_pro_id'], ['tb_produtos.pro_id'], name='tb_movimentacoes_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('mov_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
